[
    'js/constants.js',
    'js/matrix.js',
    'js/light.js',
    'js/object3d.js',
    'js/zBuffer.js',
    'js/object3dRendererBase.js',
    'js/object3dRendererFast.js',
    'js/object3dRendererFull.js',
    'js/object3dRendererFlat.js',
    'js/object3dRendererWebGL.js',
    'js/object3dRendererFactory.js',
    'js/engine3d.js',
    'js/object3dFactory.js',
    'js/input.js',
    'js/user.js',
].forEach(src => document.write('<script src="' + src + '"><\/script>'));
